apiVersion: v1
kind: Service
metadata:
  name: gamutkart-service
  labels:
    env: prod
spec:
  selector:
    app: gamutkart-pod-app
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080

